import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { Component, useState } from 'react'
import Counter from '../component/Counter.tsx';
const Home: NextPage = (): JSX.Element => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Страничка
        </h1>

        <p className={styles.description}>
          <code className={styles.code}>значение</code>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Counter key={1} key2={1} val2={10} />
          </div>
          <div className={styles.card}>
            <Counter key={2} key2={2} val2={20} />
          </div>
          <div className={styles.card}>
            <h3>test</h3>
          </div>
          <div className={styles.card}>
            <p>test</p>
          </div>

        </div>
      </main >

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/490-crocodile.svg" alt="Vercel Logo" width={72} height={72} />
          </span>
        </a>
      </footer>
    </div >
  )
}

export default Home
